from enum import Enum, auto
from typing import NamedTuple, Optional

GAME_NAME: str = "Super Smash Bros. Brawl - The Subspace Emissary"


class RoomDataType(Enum):
    standard = auto()
    optional = auto()
    boss = auto()
    horde = auto()
    brawl = auto()

class GreatMazeRegion(Enum):
    NW = auto()
    NE = auto()
    SE = auto()
    SW = auto()


class StageData(NamedTuple):
    name: str
    map_order: int


class OrangeCubeData(NamedTuple):
    stage: str
    description: str
    byte_address: str
    bit: int


class RoomData(NamedTuple):
    stage: str
    type: RoomDataType
    room_order: int  # required + optional rooms are enumerated separately
    great_maze_area: Optional[GreatMazeRegion]
    byte_address: str
    bit: int
    description: Optional[str]


class StickerData(NamedTuple):
    name: str
    series: str
    byte: str


def get_map_order(stage_name: str) -> int:
    for data in STAGES:
        if stage_name == data.name:
            return data.map_order
    return -1


STAGES: list[StageData] = [
    StageData("Midair Stadium", 0),
    StageData("Skyworld", 1),
    StageData("Sea of Clouds", 2),
    StageData("The Jungle", 3),
    StageData("The Plain", 4),
    StageData("The Lake", 5),
    StageData("The Ruined Zoo", 6),
    StageData("The Battlefield Fortress", 7),
    StageData("The Forest", 8),
    StageData("The Research Facility I", 9),
    StageData("The Lake Shore", 10),
    StageData("The Path to the Ruins", 11),
    StageData("The Cave", 12),
    StageData("The Ruins", 13),
    StageData("The Wilds I", 14),
    StageData("The Ruined Hall", 15),
    StageData("The Wilds II", 16),
    StageData("The Swamp", 17),
    StageData("The Research Facility II", 18),
    StageData("Outside the Ancient Ruins", 19),
    StageData("The Glacial Peak", 20),
    StageData("The Canyon", 21),
    StageData("Battleship Halberd Interior", 22),
    StageData("Battleship Halberd Exterior", 23),
    StageData("Battleship Halberd Bridge", 24),
    StageData("The Subspace Bomb Factory I", 25),
    StageData("The Subspace Bomb Factory II", 26),
    StageData("Entrance to Subspace", 27),
    StageData("Subspace I", 28),
    StageData("Subspace II", 29),
    StageData("The Great Maze", 30),
]

# This also includes standing trophies that count similarly for clear %
ORANGE_CUBES = [
    OrangeCubeData("Skyworld", "Orange Cube on High Platform", "9016E50C", 2),
    OrangeCubeData("The Jungle", "Orange Cube in Pit", "9016E513", 8),
    OrangeCubeData("The Jungle", "Trophy Behind Trackball Blocks", "9016E513", 7),
    OrangeCubeData("The Jungle", "Trophy by Rising Platform", "9016E513", 6),
    OrangeCubeData("The Jungle", "Orange Cube in Optional Room", "9016E513", 5),
    OrangeCubeData("The Plain", "Orange Cube Above Breakable Blocks", "9016E513", 4),
    OrangeCubeData("The Plain", "Orange Cube in High-Up Room", "9016E513", 3),
    OrangeCubeData("The Lake", "Orange Cube in Night Dimension", "9016E513", 2),
    OrangeCubeData("The Lake", "Orange Cube Along River", "9016E513", 1),
    OrangeCubeData("The Lake", "Orange Cube in River Room", "9016E512", 8),
    OrangeCubeData("The Ruined Zoo", "Orange Cube on Upper Path", "9016E512", 7),
    OrangeCubeData("The Ruined Zoo", "Orange Cube in Building", "9016E512", 6),
    OrangeCubeData(
        "The Battlefield Fortress", "Orange Cube Behind Locked Door", "9016E512", 5
    ),
    OrangeCubeData("The Battlefield Fortress", "Trophy Under Ledge", "9016E512", 4),
    OrangeCubeData(
        "The Battlefield Fortress", "Orange Cube in Minecart Room", "9016E512", 3
    ),
    OrangeCubeData("The Forest", "Orange Cube in Optional Room", "9016E512", 2),
    OrangeCubeData("The Forest", "Orange Cube Behind Exploding Blocks", "9016E512", 1),
    OrangeCubeData(
        "The Research Facility I", "Orange Cube Along Elevator", "9016E511", 8
    ),
    OrangeCubeData(
        "The Research Facility I", "Orange Cube in Far-Right Corner", "9016E511", 7
    ),
    OrangeCubeData("The Lake Shore", "Orange Cube Past Moving Wall", "9016E511", 6),
    OrangeCubeData("The Lake Shore", "Orange Cube at Upper Ledge", "9016E511", 5),
    OrangeCubeData("The Lake Shore", "Orange Cube Guarded by Shaydas", "9016E511", 4),
    OrangeCubeData("The Lake Shore", "Orange Cube at End of Level", "9016E511", 3),
    OrangeCubeData(
        "The Path to the Ruins", "Orange Cube Near Falling Blocks", "9016E511", 2
    ),
    OrangeCubeData(
        "The Path to the Ruins", "Left Trophy in Room in Pit", "9016E511", 1
    ),
    OrangeCubeData("The Path to the Ruins", "Top Trophy in Room in Pit", "9016E510", 8),
    OrangeCubeData(
        "The Path to the Ruins", "Right Trophy in Room in Pit", "9016E510", 7
    ),
    OrangeCubeData(
        "The Path to the Ruins",
        "Orange Cube on Top Ledge After Fire Pillars",
        "9016E510",
        6,
    ),
    OrangeCubeData("The Cave", "Orange Cube Below Descending Ceiling", "9016E510", 5),
    OrangeCubeData("The Cave", "Orange Cube Behind Descending Ceiling", "9016E510", 4),
    OrangeCubeData("The Cave", "Orange Cube in Falling Blocks Room", "9016E510", 3),
    OrangeCubeData("The Ruins", "Trophy on Moving Ceiling", "9016E510", 2),
    OrangeCubeData("The Ruins", "Orange Cube Above Breakable Wall", "9016E510", 1),
    OrangeCubeData("The Ruins", "Orange Cube in Roturret Door", "9016E517", 8),
    OrangeCubeData("The Wilds I", "Orange Cube in Breakable Wall", "9016E517", 7),
    OrangeCubeData("The Wilds I", "Orange Cube in High Ledge Room", "9016E517", 6),
    OrangeCubeData("The Wilds I", "Orange Cube in Room Near Cannons", "9016E517", 5),
    OrangeCubeData("The Wilds II", "Orange Cube Below Elevator", "9016E517", 4),
    OrangeCubeData("The Wilds II", "Orange Cube on Left Ledge", "9016E517", 3),
    OrangeCubeData("The Swamp", "Orange Cube on Lower Ledge", "9016E517", 2),
    OrangeCubeData("The Swamp", "Orange Cube Above Updraft", "9016E517", 1),
    OrangeCubeData("The Swamp", "Orange Cube on High Platform", "9016E516", 8),
    OrangeCubeData("The Swamp", "Trophy Behind Exploding Blocks", "9016E516", 7),
    OrangeCubeData(
        "The Research Facility II", "Orange Cube Behind Lights-On Door", "9016E516", 6
    ),
    OrangeCubeData(
        "The Research Facility II", "Orange Cube Past Moving Blocks", "9016E516", 5
    ),
    OrangeCubeData(
        "The Research Facility II", "Orange Cube by Tall Shaft", "9016E516", 4
    ),
    OrangeCubeData(
        "Outside the Ancient Ruins", "Orange Cube Above Falling Blocks", "9016E516", 3
    ),
    OrangeCubeData(
        "Outside the Ancient Ruins",
        "Orange Cube Across Falling Blocks",
        "9016E516",
        2,
    ),
    OrangeCubeData("The Glacial Peak", "Orange Cube on Right Ledge", "9016E516", 1),
    OrangeCubeData("The Glacial Peak", "Orange Cube in Cabin", "9016E515", 8),
    OrangeCubeData("The Glacial Peak", "Orange Cube Behind Icicle", "9016E515", 7),
    OrangeCubeData(
        "Battleship Halberd Interior", "Orange Cube in Hidden Room", "9016E515", 6
    ),
    OrangeCubeData("Battleship Halberd Interior", "Orange Cube by Door", "9016E515", 5),
    OrangeCubeData(
        "Battleship Halberd Interior",
        "Orange Cube Through Wall",
        "9016E515",
        4,
    ),
    OrangeCubeData(
        "Battleship Halberd Interior", "Orange Cube Above Cymul", "9016E515", 3
    ),
    OrangeCubeData(
        "Battleship Halberd Exterior", "Orange Cube in Ceiling", "9016E515", 2
    ),
    OrangeCubeData(
        "Battleship Halberd Exterior", "Orange Cube Outside Halberd", "9016E515", 1
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory I", "Orange Cube in Primid / ROB Trap", "9016E514", 8
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory I", "Orange Cube High-Up in Room", "9016E514", 7
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory II", "Orange Cube Above Spring", "9016E514", 6
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory II", "Orange Cube in Wall Jump Room", "9016E514", 5
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory II", "Orange Cube Above Burners", "9016E514", 4
    ),
    OrangeCubeData(
        "The Subspace Bomb Factory II", "Trophy Near Mite Portal", "9016E514", 3
    ),
    OrangeCubeData("Entrance to Subspace", "Trophy Behind Pillar", "9016E514", 2),
    OrangeCubeData("Subspace I", "Orange Cube in Pit / Falco Room", "9016E514", 1),
    OrangeCubeData("Subspace II", "Orange Cube Below Meta Knight", "9016E51B", 8),
    OrangeCubeData("Subspace II", "Orange Cube by Cliff", "9016E51B", 7),
    OrangeCubeData("The Great Maze NW", "Orange Cube in Room Past Pit", "9016E51B", 6),
    OrangeCubeData("The Great Maze NW", "Orange Cube by Purple Cloud", "9016E51B", 5),
    OrangeCubeData(
        "The Great Maze NW", "Orange Cube in Night Dimension", "9016E51B", 4
    ),
    OrangeCubeData(
        "The Great Maze NW", "Orange Cube Within Trackball Blocks", "9016E51B", 3
    ),
    OrangeCubeData(
        "The Great Maze NE", "Orange Cube in Ruined Zoo Area", "9016E51B", 2
    ),
    OrangeCubeData("The Great Maze NE", "Orange Cube in Halberd Area", "9016E51B", 1),
    OrangeCubeData("The Great Maze NE", "Orange Cube Above Mite Portal", "9016E51A", 8),
    OrangeCubeData(
        "The Great Maze NE",
        "Orange Cube Hidden on Conveyor",
        "9016E51A",
        7,
    ),
    OrangeCubeData(
        "The Great Maze SE", "Orange Cube on Top Ledge in Ruins Area", "9016E51A", 6
    ),
    OrangeCubeData(
        "The Great Maze SE", "Orange Cube High Up in Swamp Area", "9016E51A", 5
    ),
    OrangeCubeData(
        "The Great Maze SE", "Trophy Behind Exploding Blocks", "9016E51A", 4
    ),
    OrangeCubeData(
        "The Great Maze SE", "Orange Cube in Room Past Falco", "9016E51A", 3
    ),
    OrangeCubeData("The Great Maze SW", "Trophy on Moving Ceiling", "9016E51A", 2),
    OrangeCubeData("The Great Maze SW", "Orange Cube in Windy Area", "9016E51A", 1),
]

STICKERS = [
    StickerData("Instructor", "Pilotwings", "9017C398"),
    StickerData("Aijou Boom no Ya", "Sennen Kazoku", "9017C39A"),
    StickerData("Special Token", "Metroid Pinball", "9017C39C"),
    StickerData("Ocarina of Time", "Zelda: Ocarina of Time", "9017C39E"),
    StickerData("King Bulblin & Lord Bullbo", "Zelda: TP", "9017C3A0"),
    StickerData("Noki", "Super Mario Sunshine", "9017C3A2"),
    StickerData("Dunning Smith", "Hotel Dusk: Room 215", "9017C3A4"),
    StickerData("Daisy", "Super Mario Strikers", "9017C3A6"),
    StickerData("Goldeen", "Pokémon series", "9017C3A8"),
    StickerData("Bonkers", "Kirby: Squeak Squad", "9017C3AA"),
    StickerData("Plum", "Mario Golf", "9017C3AC"),
    StickerData("Telly", "Chibi-Robo", "9017C3AE"),
    StickerData("Enguarde", "Donkey Kong Country", "9017C3B0"),
    StickerData("Fairy", "Zelda: Twilight Princess", "9017C3B2"),
    StickerData("Dr. Lobe", "Big Brain Academy", "9017C3B4"),
    StickerData("Jirachi", "Pokémon series", "9017C3B6"),
    StickerData("Young Cricket", "WarioWare: Smooth Moves", "9017C3B8"),
    StickerData("Dr. Crygor", "WarioWare: Touched!", "9017C3BA"),
    StickerData("Moon Fairy Seren", "Nintendo Puzzle Collection", "9017C3BC"),
    StickerData("Kamek", "Yoshi's Island", "9017C3BE"),
    StickerData("Lucas", "Mother 3", "9017C3C0"),
    StickerData("Bone Dragon", "Yoshi's Story", "9017C3C2"),
    StickerData("Sable", "Animal Crossing: WW", "9017C3C4"),
    StickerData("Golden Fox", "F-Zero GX", "9017C3C6"),
    StickerData("Solid Snake", "MGS2: Sons of Liberty", "9017C3C8"),
    StickerData("Propeller Shy Guy", "Yoshi's Story", "9017C3CA"),
    StickerData("Deoxys", "Pokémon series", "9017C3CC"),
    StickerData("Mist", "Fire Emblem: Path of Radiance", "9017C3CE"),
    StickerData("Little Saucer", "Mother", "9017C3D0"),
    StickerData("Electroplankton", "Electroplankton", "9017C3D2"),
    StickerData("Tetra", "Zelda: Wind Waker", "9017C3D4"),
    StickerData("Boundish", "Digiluxe", "9017C3D6"),
    StickerData("Piplup", "Pokémon series", "9017C3D8"),
    StickerData("Seiuchi-kun", "Densetsu no Stafy 3", "9017C3DA"),
    StickerData("Morris", "Elite Beat Agents", "9017C3DC"),
    StickerData("Sami", "Advance Wars", "9017C3DE"),
    StickerData("Wild Gunman", "Wild Gunman", "9017C3E0"),
    StickerData("Joan", "Animal Crossing: WW", "9017C3E2"),
    StickerData("Teddy", "Mother", "9017C3E4"),
    StickerData("Cell Phone", "Kirby & The Amazing Mirror", "9017C3E6"),
    StickerData("Eliwood", "Fire Emblem", "9017C3E8"),
    StickerData("Mario & Luigi", "Mario & Luigi: SS", "9017C3EA"),
    StickerData("Klaptrap", "Donkey Kong Country", "9017C3EC"),
    StickerData("Jill", "Drill Dozer", "9017C3EE"),
    StickerData("Sukapon", "Joy Mech Fight", "9017C3F0"),
    StickerData("Zora", "Zelda: Ocarina of Time", "9017C3F2"),
    StickerData("Junior", "Donkey Kong Jr.", "9017C3F4"),
    StickerData("Toad", "Mario Party 6", "9017C3F6"),
    StickerData("Eldstar", "Mario Party 5", "9017C3F8"),
    StickerData("Pelly", "Animal Crossing: WW", "9017C3FA"),
    StickerData("Welsh Corgi", "Nintendogs", "9017C3FC"),
    StickerData("Mega Mushroom", "New Super Mario Bros.", "9017C3FE"),
    StickerData("Fire Flower", "New Super Mario Bros.", "9017C400"),
    StickerData("Midna & Wolf Link", "Zelda: Twilight Princess", "9017C402"),
    StickerData("Pit", "Kid Icarus", "9017C404"),
    StickerData("DK", "Mario Superstar Baseball", "9017C406"),
    StickerData("Stafy", "Densetsu no Stafy 2", "9017C408"),
    StickerData("Ningyou Kouchuu Viigaru", "Chosoju Mecha MG", "9017C40A"),
    StickerData("Boulder", "Excite Truck", "9017C40C"),
    StickerData("Togepi", "Pokémon series", "9017C40E"),
    StickerData("Ashley", "Trace Memory", "9017C410"),
    StickerData("Dark Suit Samus", "Metroid Prime 2 Echoes", "9017C412"),
    StickerData("Charizard", "Pokémon series", "9017C414"),
    StickerData("Papa", "Chibi-Robo", "9017C416"),
    StickerData("Crazy Redd", "Animal Crossing: WW", "9017C418"),
    StickerData("Warrior Ing", "Metroid Prime 2 Echoes", "9017C41A"),
    StickerData("Bubble Baby Mario", "Yoshi's Island", "9017C41C"),
    StickerData("Jill & Drill Dozer", "Drill Dozer", "9017C41E"),
    StickerData("Kat", "WarioWare: Touched!", "9017C420"),
    StickerData("Mario", "Super Paper Mario", "9017C422"),
    StickerData("Aryll", "Zelda: Wind Waker", "9017C424"),
    StickerData("Cupit", "Sennen Kazoku", "9017C426"),
    StickerData("King Dodongo", "Zelda: Ocarina of Time", "9017C428"),
    StickerData("Boy", "Magical Starsign", "9017C42A"),
    StickerData("Item Box", "Mario Kart: DD!!", "9017C42C"),
    StickerData("Ray", "Custom Robo", "9017C42E"),
    StickerData("Waluigi", "Mario Superstar Baseball", "9017C430"),
    StickerData("Slippy", "Star Fox: Assault", "9017C432"),
    StickerData("Coin", "New Super Mario Bros.", "9017C434"),
    StickerData("Deku Nut", "Zelda: Ocarina of Time", "9017C436"),
    StickerData("Zelda", "Zelda: Ocarina of Time", "9017C438"),
    StickerData("King Zora", "Zelda: Ocarina of Time", "9017C43A"),
    StickerData("Pit", "Kid Icarus: OM&M", "9017C43C"),
    StickerData("Shiba Inu", "Nintendogs", "9017C43E"),
    StickerData("Bullet Bill", "New Super Mario Bros.", "9017C440"),
    StickerData("Shroob", "Mario & Luigi: PiT", "9017C442"),
    StickerData("Xananab", "DK Jungle Climber", "9017C444"),
    StickerData("Chef Kawasaki", "Kirby Super Star", "9017C446"),
    StickerData("Kyogre", "Pokémon series", "9017C448"),
    StickerData("Dr. Lobe", "Big Brain Academy: WD", "9017C44A"),
    StickerData("Hylian Shield", "Zelda: Minish Cap", "9017C44C"),
    StickerData("Celeste", "Animal Crossing: WW", "9017C44E"),
    StickerData("Lanky Kong", "DK64", "9017C450"),
    StickerData("Solid Snake", "MGS: The Twin Snakes", "9017C452"),
    StickerData("Pete", "Animal Crossing: WW", "9017C454"),
    StickerData("The Great Fairy", "Zelda: Wind Waker", "9017C456"),
    StickerData("Ninten", "Mother", "9017C458"),
    StickerData("Poo", "EarthBound", "9017C45A"),
    StickerData("Robot", "Mario Kart DS JP", "9017C45C"),
    StickerData("Daphnes Nohansen Hyrule", "Zelda: WW", "9017C45E"),
    StickerData("Box Boxer", "Kirby: Squeak Squad", "9017C460"),
    StickerData("Sabure Prince", "Kaeru no Tame ni Kane wa Naru", "9017C462"),
    StickerData("Jimmy T.", "WarioWare: MPG", "9017C464"),
    StickerData("Ryota Hayami", "Wave Race BS", "9017C466"),
    StickerData("Phantom Ganon", "Zelda: Ocarina of Time", "9017C468"),
    StickerData("Nana", "Ice Climber", "9017C46A"),
    StickerData("Gomar & Shioh", "F-Zero GX", "9017C46C"),
    StickerData("Blue Falcon", "F-Zero GX", "9017C46E"),
    StickerData("Bullet Blaster", "Mario Kart: DD!!", "9017C470"),
    StickerData("Cook Kirby", "Kirby Super Star", "9017C472"),
    StickerData("Jet the Hawk", "Sonic Riders", "9017C474"),
    StickerData("Amy Rose", "Sonic CD", "9017C476"),
    StickerData("Slippy", "Star Fox 64", "9017C478"),
    StickerData("Egg", "Game & Watch", "9017C47A"),
    StickerData("Needle Kirby", "Kirby 64", "9017C47C"),
    StickerData("King Dedede", "Kirby: Squeak Squad", "9017C47E"),
    StickerData("Krystal", "Star Fox: Assault", "9017C480"),
    StickerData("Rouge the Bat", "Sonic Adventure 2: Battle", "9017C482"),
    StickerData("Epona & Link", "Zelda: Ocarina of Time", "9017C484"),
    StickerData("Petey Piranha", "Mario Strikers Charged", "9017C486"),
    StickerData("Panther", "Star Fox Command", "9017C488"),
    StickerData("Mach Rider", "Mach Rider", "9017C48A"),
    StickerData("Erazor Djinn", "Sonic & the Secret Rings", "9017C48C"),
    StickerData("Chozo Statue", "Metroid II", "9017C48E"),
    StickerData("White Pikmin", "Pikmin 2", "9017C490"),
    StickerData("Bowser", "Mario Power Tennis", "9017C492"),
    StickerData("Mokka", "Magical Starsign", "9017C494"),
    StickerData("Big the Cat", "Sonic Adventure Director's Cut", "9017C496"),
    StickerData("Dark Samus", "Metroid Prime 2 Echoes", "9017C498"),
    StickerData("Makar", "Zelda: Wind Waker", "9017C49A"),
    StickerData("Hooktail", "Paper Mario: TTYD", "9017C49C"),
    StickerData("E-123 Omega", "Sonic Heroes", "9017C49E"),
    StickerData("Starman", "Kirby: Squeak Squad", "9017C4A0"),
    StickerData("Metal Sonic", "Sonic CD", "9017C4A2"),
    StickerData("Luigi & Baby Luigi", "Mario & Luigi: PiT", "9017C4A4"),
    StickerData("Dr. Eggman", "Sonic The Hedgehog", "9017C4A6"),
    StickerData("Chao", "Sonic Adventure Director's Cut", "9017C4A8"),
    StickerData("Blaze the Cat", "Sonic Rush", "9017C4AA"),
    StickerData("Commander Kahn", "Elite Beat Agents", "9017C4AC"),
    StickerData("Rambi", "Donkey Kong Country", "9017C4AE"),
    StickerData("Tingle", "Tingle's Rupeeland", "9017C4B0"),
    StickerData("Hajime Tanaka", "Ouendan 2", "9017C4B2"),
    StickerData("Barrel Train", "Mario Kart: DD!!", "9017C4B4"),
    StickerData("Lakitu", "Mario Kart: Super Circuit", "9017C4B6"),
    StickerData("Red Gazelle", "F-Zero GX", "9017C4B8"),
    StickerData("Banana Coin", "DK64", "9017C4BA"),
    StickerData("Peach", "Super Princess Peach", "9017C4BC"),
    StickerData("Sayaka Amemiya", "Ouendan 2", "9017C4BE"),
    StickerData("Chibi-Robo", "Chibi-Robo", "9017C4C0"),
    StickerData("Derek", "Elite Beat Agents", "9017C4C2"),
    StickerData("Gale Hawg", "DK Jungle Beat", "9017C4C4"),
    StickerData("Octoman", "F-Zero GX", "9017C4C6"),
    StickerData("Nruff", "Kirby 64", "9017C4C8"),
    StickerData("Leon", "Star Fox: Assault", "9017C4CA"),
    StickerData("Diddy Kong", "Donkey Kong Country", "9017C4CC"),
    StickerData("Pak E. Derm", "Yoshi's Story", "9017C4CE"),
    StickerData("Peppy", "Star Fox: Assault", "9017C4D0"),
    StickerData("Penny", "WarioWare: Smooth Moves", "9017C4D2"),
    StickerData("Myrrh", "Fire Emblem: The Sacred Stones", "9017C4D4"),
    StickerData("Toadette", "Mario Party 6", "9017C4D6"),
    StickerData("Claus", "Mother 3", "9017C4D8"),
    StickerData("Magkid", "Slide Adventure MAGKID", "9017C4DA"),
    StickerData("Chain Chomp", "Mario Party 8", "9017C4DC"),
    StickerData("Master Belch", "EarthBound", "9017C4DE"),
    StickerData("Leon", "Star Fox Command", "9017C4E0"),
    StickerData("Joshua", "Fire Emblem: The Sacred Stones", "9017C4E2"),
    StickerData("Snorlax", "Pokémon series", "9017C4E4"),
    StickerData("Free Ranger", "Chibi Robo: Park Patrol", "9017C4E6"),
    StickerData("Entei", "Pokémon series", "9017C4E8"),
    StickerData("Orbulon", "WarioWare: MPG", "9017C4EA"),
    StickerData("Celebi", "Pokémon series", "9017C4EC"),
    StickerData("Crazee Dayzee", "Yoshi's Island DS", "9017C4EE"),
    StickerData("Eggplant Wizard", "Kid Icarus", "9017C4F0"),
    StickerData("Banana Bunch", "DK: Barrel Blast", "9017C4F2"),
    StickerData("Mario & Yoshi", "Super Mario Sunshine", "9017C4F4"),
    StickerData("Cranky Kong", "Donkey Konga 3 JP", "9017C4F6"),
    StickerData("Andy", "Advance Wars", "9017C4F8"),
    StickerData("Kamek", "Yoshi Touch & Go", "9017C4FA"),
    StickerData("Flint", "Mother 3", "9017C4FC"),
    StickerData("HP Pot", "Magical Starsign", "9017C4FE"),
    StickerData("Mad Truck", "Mother", "9017C500"),
    StickerData("Wrinkly Kong", "DK: King of Swing", "9017C502"),
    StickerData("Hylian Shield", "Zelda: Twilight Princess", "9017C504"),
    StickerData("Tingle", "Zelda: Wind Waker", "9017C506"),
    StickerData("Lantern", "Zelda: Twilight Princess", "9017C508"),
    StickerData("Chibi-Robo", "Chibi Robo: Park Patrol", "9017C50A"),
    StickerData("General Guy", "Paper Mario", "9017C50C"),
    StickerData("Meta Knight Ball", "Kirby Canvas Curse", "9017C50E"),
    StickerData("Peach", "Super Mario Bros. 2", "9017C510"),
    StickerData("Big Switch", "Kirby & The Amazing Mirror", "9017C512"),
    StickerData("Dzuke-chan", "English Training", "9017C514"),
    StickerData("Andrew", "Star Fox: Assault", "9017C516"),
    StickerData("Stuffwell", "Mario & Luigi: PiT", "9017C518"),
    StickerData("Blipper", "Kirby: Squeak Squad", "9017C51A"),
    StickerData("Weavel", "Metroid Prime Hunters", "9017C51C"),
    StickerData("Bowser", "Super Paper Mario", "9017C51E"),
    StickerData("Rawk Hawk", "Paper Mario: TTYD", "9017C520"),
    StickerData("Octopus", "Game & Watch", "9017C522"),
    StickerData("Postman", "Zelda: Twilight Princess", "9017C524"),
    StickerData("Happy Mask Salesman", "Zelda: MM", "9017C526"),
    StickerData("Shy Guy", "Yoshi's Story", "9017C528"),
    StickerData("Kai Doumeki", "Ouendan 2", "9017C52A"),
    StickerData("Party Monkey", "DK Jungle Beat", "9017C52C"),
    StickerData("Shine Sprite", "Super Mario Sunshine", "9017C52E"),
    StickerData("Goombella", "Paper Mario: TTYD", "9017C530"),
    StickerData("Bowser Jr.", "Super Mario Sunshine", "9017C532"),
    StickerData("Mushroom", "New Super Mario Bros.", "9017C534"),
    StickerData("Deku Baba", "Zelda: Ocarina of Time", "9017C536"),
    StickerData("Girl", "Magical Vacation", "9017C538"),
    StickerData("Bow", "Paper Mario", "9017C53A"),
    StickerData("Kumatora", "Mother 3", "9017C53C"),
    StickerData("Fox", "Star Fox", "9017C53E"),
    StickerData("Orbiter", "Digiluxe", "9017C540"),
    StickerData("Spiny", "New Super Mario Bros.", "9017C542"),
    StickerData("Chromatron", "Digiluxe", "9017C544"),
    StickerData("Lightning", "Mario Kart DS", "9017C546"),
    StickerData("Suicune", "Pokémon series", "9017C548"),
    StickerData("Tractor Trailer", "Wild Trax", "9017C54A"),
    StickerData("Rad", "Excite Truck", "9017C54C"),
    StickerData("Master Miller", "MGS: The Twin Snakes", "9017C54E"),
    StickerData("Donbe", "Shin Onigashima", "9017C550"),
    StickerData("Reaper & Reapette", "Kid Icarus", "9017C552"),
    StickerData("The Black Knight", "Fire Emblem: PoR", "9017C554"),
    StickerData("Starship", "Metroid Prime Hunters", "9017C556"),
    StickerData("Yoshi", "Mario Party 2", "9017C558"),
    StickerData("Yellow Virus", "Nintendo Puzzle Collection", "9017C55A"),
    StickerData("Panel", "Nintendo Puzzle Collection", "9017C55C"),
    StickerData("Kirby", "Kirby & The Amazing Mirror", "9017C55E"),
    StickerData("Flower Fairy Lip", "Nintendo Puzzle Collection", "9017C560"),
    StickerData("Mr. Saturn", "EarthBound", "9017C562"),
    StickerData("King Dedede", "Kirby Super Star", "9017C564"),
    StickerData("Marth", "Fire Emblem: Monsho no Nazo", "9017C566"),
    StickerData("Vermin", "Game & Watch", "9017C568"),
    StickerData("Falco", "Star Fox 64", "9017C56A"),
    StickerData("Fly Guy", "Mario Power Tennis", "9017C56C"),
    StickerData("Chunky Kong", "DK64", "9017C56E"),
    StickerData("Spitz", "WarioWare: MPG", "9017C570"),
    StickerData("Capt. Falcon", "F-Zero GX", "9017C572"),
    StickerData("Mei Ling", "MGS: The Twin Snakes", "9017C574"),
    StickerData("Burt the Bashful", "Yoshi's Island", "9017C576"),
    StickerData("Link with Goron Mask", "Zelda: MM", "9017C578"),
    StickerData("Young Zelda", "Zelda: Ocarina of Time", "9017C57A"),
    StickerData("Mabel", "Animal Crossing: WW", "9017C57C"),
    StickerData("Metroid", "Metroid Pinball", "9017C57E"),
    StickerData("Blue Pikmin", "Pikmin", "9017C580"),
    StickerData("Ridley", "Metroid", "9017C582"),
    StickerData("Samus", "Metroid", "9017C584"),
    StickerData("Otacon", "MGS2: Sons of Liberty", "9017C586"),
    StickerData("Samus", "Metroid Fusion", "9017C588"),
    StickerData("Wario Car", "Mario Kart: DD!!", "9017C58A"),
    StickerData("Annie", "Custom Robo V2", "9017C58C"),
    StickerData("Dyna Blade", "Kirby Super Star", "9017C58E"),
    StickerData("O'Chunks", "Super Paper Mario", "9017C590"),
    StickerData("Toad", "Mario Party 7", "9017C592"),
    StickerData("The Boss", "MGS3: Snake Eater", "9017C594"),
    StickerData("Zora Link", "Zelda: Majora's Mask", "9017C596"),
    StickerData("Ike", "Fire Emblem: Path of Radiance", "9017C598"),
    StickerData("Espio the Chameleon", "Knuckles' Chaotix", "9017C59A"),
    StickerData("Brewster", "Animal Crossing: WW", "9017C59C"),
    StickerData("Fox", "Star Fox Command", "9017C59E"),
    StickerData("Wario-Man", "WarioWare: Touched!", "9017C5A0"),
    StickerData("Ness", "EarthBound", "9017C5A2"),
    StickerData("Mr. Saturn", "Mother 3", "9017C5A4"),
    StickerData("Boxy", "Kirby: Squeak Squad", "9017C5A6"),
    StickerData("Fox", "Star Fox: Assault", "9017C5A8"),
    StickerData("Energy Tank", "Metroid", "9017C5AA"),
    StickerData("Reclining Red Pikmin", "Pikmin 2", "9017C5AC"),
    StickerData("Digidrive", "Digiluxe", "9017C5AE"),
    StickerData("Starman", "New Super Mario Bros.", "9017C5B0"),
    StickerData("Yellow Pellet", "Pikmin 2", "9017C5B2"),
    StickerData("Ganondorf", "Zelda: Ocarina of Time", "9017C5B4"),
    StickerData("Shadow Beast", "Zelda: Twilight Princess", "9017C5B6"),
    StickerData("DK with Barrel", "Mario vs. DK 2: MotM", "9017C5B8"),
    StickerData("Vector the Crocodile", "Knuckles' Chaotix", "9017C5BA"),
    StickerData("Fat Hockey Player", "Ice Hockey", "9017C5BC"),
    StickerData("Eva", "MGS3: Snake Eater", "9017C5BE"),
    StickerData("Cream the Rabbit & Cheese", "Sonic Advance 2", "9017C5C0"),
    StickerData("Bowser Jr.", "Mario Superstar Baseball", "9017C5C2"),
    StickerData("Link & Pigs", "Zelda: Wind Waker", "9017C5C4"),
    StickerData("Ray 01", "Custom Robo: BR", "9017C5C6"),
    StickerData("Donkey Kong Jr.", "Mario Tennis", "9017C5C8"),
    StickerData("Max", "Advance Wars", "9017C5CA"),
    StickerData("Zebes Inhabitant", "Metroid Fusion", "9017C5CC"),
    StickerData("18-Volt", "WarioWare: Touched!", "9017C5CE"),
    StickerData("Skull Kid", "Zelda: Majora's Mask", "9017C5D0"),
    StickerData("Funky Kong", "Donkey Konga 3 JP", "9017C5D2"),
    StickerData("Lilina", "Fire Emblem: The Binding Blade", "9017C5D4"),
    StickerData("Bonsly", "Pokémon series", "9017C5D6"),
    StickerData("Ray MKIII", "Custom Robo Arena", "9017C5D8"),
    StickerData("Warrior Mech Gauss", "Chosoju Mecha MG", "9017C5DA"),
    StickerData("Starship", "Metroid Fusion", "9017C5DC"),
    StickerData("Balloon Fighter", "Balloon Fight", "9017C5DE"),
    StickerData("Wobbuffet", "Pokémon series", "9017C5E0"),
    StickerData("9-Volt", "WarioWare: Touched!", "9017C5E2"),
    StickerData("Mew", "Pokémon series", "9017C5E4"),
    StickerData("Boy", "Magical Vacation", "9017C5E6"),
    StickerData("F-Type", "Wild Trax", "9017C5E8"),
    StickerData("Bowser", "DDR: Mario Mix", "9017C5EA"),
    StickerData("Gracie", "Animal Crossing: WW", "9017C5EC"),
    StickerData("Blathers", "Animal Crossing: WW", "9017C5EE"),
    StickerData("General Pepper", "Star Fox: Assault", "9017C5F0"),
    StickerData("Stork Stop", "Yoshi's Island DS", "9017C5F2"),
    StickerData("Starman", "EarthBound", "9017C5F4"),
    StickerData("Rakensen", "Custom Robo: BR", "9017C5F6"),
    StickerData("Luminoth", "Metroid Prime 2 Echoes", "9017C5F8"),
    StickerData("Weavile", "Pokémon series", "9017C5FA"),
    StickerData("HM Mech Rosa", "Chosoju Mecha MG", "9017C5FC"),
    StickerData("Hanenbow", "Electroplankton", "9017C5FE"),
    StickerData("Salvatore", "Zelda: Wind Waker", "9017C600"),
    StickerData("Red Fire", "Mario Kart: DD!!", "9017C602"),
    StickerData("Ho-Oh", "Pokémon series", "9017C604"),
    StickerData("Hot Head", "Kirby: Squeak Squad", "9017C606"),
    StickerData("Materu", "Densetsu no Stafy 4", "9017C608"),
    StickerData("Perry", "Super Princess Peach", "9017C60A"),
    StickerData("Manaphy", "Pokémon series", "9017C60C"),
    StickerData("Link", "The Legend of Zelda", "9017C60E"),
    StickerData("Toadsworth", "Super Mario Sunshine", "9017C610"),
    StickerData("Stapy", "Densetsu no Stafy 3", "9017C612"),
    StickerData("Hoofer", "DK Jungle Beat", "9017C614"),
    StickerData("Monster", "FGPII: 3D Hot Rally", "9017C616"),
    StickerData("Kanden", "Metroid Prime Hunters", "9017C618"),
    StickerData("Groudon", "Pokémon series", "9017C61A"),
    StickerData("Deku Link", "Zelda: Majora's Mask", "9017C61C"),
    StickerData("Kalypso", "DK: Barrel Blast", "9017C61E"),
    StickerData("Gleeok", "The Legend of Zelda", "9017C620"),
    StickerData("Lon Lon Milk", "Zelda: Ocarina of Time", "9017C622"),
    StickerData("Spiny Shell", "Mario Kart: DD!!", "9017C624"),
    StickerData("Malo", "Zelda: Twilight Princess", "9017C626"),
    StickerData("Kritter", "DK: King of Swing", "9017C628"),
    StickerData("Purple Pikmin", "Pikmin 2", "9017C62A"),
    StickerData("Mini Mario", "Mario vs. DK 2: MotM", "9017C62C"),
    StickerData("Booker", "Animal Crossing: WW", "9017C62E"),
    StickerData("Chef", "Shaberu! DS Cooking Navi", "9017C630"),
    StickerData("Cupid Kirby", "Kirby & The Amazing Mirror", "9017C632"),
    StickerData("Jake", "Advance Wars: DS", "9017C634"),
    StickerData("Diddy Kong", "Mario Superstar Baseball", "9017C636"),
    StickerData("Rosie", "Animal Crossing: WW", "9017C638"),
    StickerData("Running Zero Suit Samus", "Metroid: ZM", "9017C63A"),
    StickerData("Micaiah", "Fire Emblem: Radiant Dawn", "9017C63C"),
    StickerData("Bowser", "Mario Kart 64", "9017C63E"),
    StickerData("ReDead", "Zelda: Ocarina of Time", "9017C640"),
    StickerData("Captain", "Trace Memory", "9017C642"),
    StickerData("Firefly", "Excite Truck", "9017C644"),
    StickerData("Jewel Fairy Ruby", "Nintendo Puzzle Collection", "9017C646"),
    StickerData("Ana", "Mother", "9017C648"),
    StickerData("Gordo", "Kirby: Squeak Squad", "9017C64A"),
    StickerData("Wolfen", "Star Fox 64", "9017C64C"),
    StickerData("Stafy", "Densetsu no Stafy", "9017C64E"),
    StickerData("Super Mario Bros.", "Super Mario Bros.", "9017C650"),
    StickerData("Pokémon Trainer", "Pokémon series", "9017C652"),
    StickerData("Ninian", "Fire Emblem", "9017C654"),
    StickerData("Girl", "Animal Crossing: WW", "9017C656"),
    StickerData("Seal Head", "Custom Robo: BR", "9017C658"),
    StickerData("Wendell", "Animal Crossing: WW", "9017C65A"),
    StickerData("Fire Stingray", "F-Zero GX", "9017C65C"),
    StickerData("Gulpin", "Pokémon series", "9017C65E"),
    StickerData("Link", "Zelda: Wind Waker", "9017C660"),
    StickerData("Kirsh", "Magical Vacation", "9017C662"),
    StickerData("Baby Mario", "Yoshi's Island", "9017C664"),
    StickerData("Akari Hayami", "1080° Avalanche", "9017C666"),
    StickerData("Kammy Koopa", "Paper Mario", "9017C668"),
    StickerData("Colin", "Zelda: Twilight Princess", "9017C66A"),
    StickerData("Staryu", "Pokémon series", "9017C66C"),
    StickerData("Ricky Winterborn", "1080° Avalanche", "9017C66E"),
    StickerData("Hinawa", "Mother 3", "9017C670"),
    StickerData("Yellow Pikmin", "Pikmin", "9017C672"),
    StickerData("Yakuman Player", "Yakuman", "9017C674"),
    StickerData("Metagross", "Pokémon series", "9017C676"),
    StickerData("Cackletta", "Mario & Luigi: SS", "9017C678"),
    StickerData("Bullfrog", "Star Fox Command", "9017C67A"),
    StickerData("Parachute", "Game & Watch", "9017C67C"),
    StickerData("Whispy Woods", "Kirby Super Star", "9017C67E"),
    StickerData("Wild Goose", "F-Zero GX", "9017C680"),
    StickerData("King K. Rool", "DK64", "9017C682"),
    StickerData("Wolf", "Star Fox: Assault", "9017C684"),
    StickerData("Porky", "EarthBound", "9017C686"),
    StickerData("New Age Retro Hippie", "Mother", "9017C688"),
    StickerData("Ludwig von Koopa", "Super Mario Bros. 3", "9017C68A"),
    StickerData("Ike", "Fire Emblem: Radiant Dawn", "9017C68C"),
    StickerData("Dry Bones", "Mario Party 7", "9017C68E"),
    StickerData("Rachel", "Advance Wars: DS", "9017C690"),
    StickerData("Lakitu", "New Super Mario Bros.", "9017C692"),
    StickerData("Latias & Latios", "Pokémon series", "9017C694"),
    StickerData("Lugia", "Pokémon series", "9017C696"),
    StickerData("Capt. Falcon", "F-Zero X", "9017C698"),
    StickerData("Ashley Viewing DTS", "Trace Memory", "9017C69A"),
    StickerData("Chef", "Game & Watch", "9017C69C"),
    StickerData("Donkey Kong", "Donkey Kong Country", "9017C69E"),
    StickerData("Dixie Kong", "Donkey Konga 2", "9017C6A0"),
    StickerData("Tiny Wario", "Virtual Boy Wario Land", "9017C6A2"),
    StickerData("Kamisama", "Sennen Kazoku", "9017C6A4"),
    StickerData("Kafei & Keaton Mask", "Zelda: MM", "9017C6A6"),
    StickerData("Lyn", "Fire Emblem", "9017C6A8"),
    StickerData("Zero Suit Samus", "Metroid: Zero Mission", "9017C6AA"),
    StickerData("Shahra", "Sonic & the Secret Rings", "9017C6AC"),
    StickerData("Sonic the Hedgehog", "Sonic The Hedgehog", "9017C6AE"),
    StickerData("Robo Cube", "Custom Robo: BR", "9017C6B0"),
    StickerData("Zelda", "Zelda: Link to the Past", "9017C6B2"),
    StickerData("Pinkle", "Tingle's Rupeeland", "9017C6B4"),
    StickerData("King of Red Lions & Link", "Zelda: WW", "9017C6B6"),
    StickerData("Charmy Bee", "Knuckles' Chaotix", "9017C6B8"),
    StickerData("E-102 Gamma", "Sonic Adventure Director's Cut", "9017C6BA"),
    StickerData("Chikorita", "Pokémon series", "9017C6BC"),
    StickerData("Rob Haywood", "Wave Race BS", "9017C6BE"),
    StickerData("Red Pellet Flower", "Pikmin 2", "9017C6C0"),
    StickerData("Ganondorf", "Zelda: Wind Waker", "9017C6C2"),
    StickerData("Shadow the Hedgehog", "Sonic Adventure 2: Battle", "9017C6C4"),
    StickerData("R.O.B.", "Mario Kart DS US", "9017C6C6"),
    StickerData("Storm the Albatross", "Sonic Riders", "9017C6C8"),
    StickerData("Balloon Fight Enemy", "Balloon Fight", "9017C6CA"),
    StickerData("K.K. Slider", "Animal Crossing: WW", "9017C6CC"),
    StickerData("Knuckles the Echidna", "Sonic The Hedgehog 3", "9017C6CE"),
    StickerData("Wario", "Super Mario 64 DS", "9017C6D0"),
    StickerData("Mother Brain", "Metroid: Zero Mission", "9017C6D2"),
    StickerData('Miles "Tails" Prower', "Sonic The Hedgehog 2", "9017C6D4"),
    StickerData("Shagohod", "MGS3: Snake Eater", "9017C6D6"),
    StickerData("Mouser", "Super Mario Bros. 2", "9017C6D8"),
    StickerData("Kooper", "Paper Mario", "9017C6DA"),
    StickerData("Bowser Coin", "Mario Party 6", "9017C6DC"),
    StickerData("J", "Elite Beat Agents", "9017C6DE"),
    StickerData("Sidestepper", "Mario Bros", "9017C6E0"),
    StickerData("Kapp'n", "Animal Crossing: WW", "9017C6E2"),
    StickerData("Takamaru", "Nazo no Murasamejo", "9017C6E4"),
    StickerData("Lyle", "Animal Crossing: WW", "9017C6E6"),
    StickerData("Yadokarita", "Densetsu no Stafy", "9017C6E8"),
    StickerData("Peppy", "Star Fox 64", "9017C6EA"),
    StickerData("Dr. Mario", "Nintendo Puzzle Collection", "9017C6EC"),
    StickerData("Ballyhoo & Big Top", "Mario Party 8", "9017C6EE"),
    StickerData("Training Academy Coach", "X", "9017C6F0"),
    StickerData("Kururin", "Kururin Paradise", "9017C6F2"),
    StickerData("Kirby", "Kirby 64", "9017C6F4"),
    StickerData("Copper", "Animal Crossing: WW", "9017C6F6"),
    StickerData("Linebeck", "Zelda: Phantom Hourglass", "9017C6F8"),
    StickerData("Greil", "Fire Emblem: Path of Radiance", "9017C6FA"),
    StickerData("Harriet", "Animal Crossing: WW", "9017C6FC"),
    StickerData("Panther", "Star Fox: Assault", "9017C6FE"),
    StickerData("Chihuahua", "Nintendogs", "9017C700"),
    StickerData("Manhole", "Game & Watch", "9017C702"),
    StickerData("Link's Grandma", "Zelda: Wind Waker", "9017C704"),
    StickerData("Kyorosuke", "Densetsu no Stafy 4", "9017C706"),
    StickerData("Fox", "Star Fox 64", "9017C708"),
    StickerData("Louie", "Pikmin 2", "9017C70A"),
    StickerData("Musketeer Daltania", "Chosoju Mecha MG", "9017C70C"),
    StickerData("Mr. EAD", "F-Zero GX", "9017C70E"),
    StickerData("Meowth", "Pokémon series", "9017C710"),
    StickerData("Daroach", "Kirby: Squeak Squad", "9017C712"),
    StickerData("Metroid", "Metroid: Zero Mission", "9017C714"),
    StickerData("Nanocarp", "Electroplankton", "9017C716"),
    StickerData("9-Volt", "WarioWare: MPG", "9017C718"),
    StickerData("Dr. Stewart", "F-Zero GX", "9017C71A"),
    StickerData("Red Virus", "Nintendo Puzzle Collection", "9017C71C"),
    StickerData("Banana", "Mario Kart DS", "9017C71E"),
    StickerData("ROB 64", "Star Fox: Assault", "9017C720"),
    StickerData("Shiida", "Fire Emblem: Monsho no Nazo", "9017C722"),
    StickerData("Valoo", "Zelda: Wind Waker", "9017C724"),
    StickerData("Dribble", "WarioWare: MPG", "9017C726"),
    StickerData("Link", "Zelda: Twilight Princess", "9017C728"),
    StickerData("Mona", "WarioWare: Touched!", "9017C72A"),
    StickerData("Iron Tiger", "F-Zero GX", "9017C72C"),
    StickerData("ROB", "Star Fox Adventures", "9017C72E"),
    StickerData("Luigi", "Mario & Luigi: SS", "9017C730"),
    StickerData("Toadsworth", "Mario & Luigi: PiT", "9017C732"),
    StickerData("Duck", "Duck Hunt", "9017C734"),
    StickerData("Wiggler", "Mario Power Tennis", "9017C736"),
    StickerData("Super Baby", "Yoshi's Island DS", "9017C738"),
    StickerData("Flower Icon", "Paper Mario: TTYD", "9017C73A"),
    StickerData("Grutch", "Drill Dozer", "9017C73C"),
    StickerData("Cheep Cheep", "New Super Mario Bros.", "9017C73E"),
    StickerData("Brighton", "Mario Party 6", "9017C740"),
    StickerData("Male Pianta", "Super Mario Sunshine", "9017C742"),
    StickerData("Boy", "Animal Crossing: WW", "9017C744"),
    StickerData("Fire", "Game & Watch", "9017C746"),
    StickerData("Pigma", "Star Fox: Assault", "9017C748"),
    StickerData("Midori Mushi", "Slide Adventure MAGKID", "9017C74A"),
    StickerData("Mila", "Hotel Dusk: Room 215", "9017C74C"),
    StickerData("Power Jump Badge", "Paper Mario", "9017C74E"),
    StickerData("Toad & Toadette", "Mario Party 7", "9017C750"),
    StickerData("Spinner", "Zelda: Twilight Princess", "9017C752"),
    StickerData("Yoshi Ship", "Yoshi Topsy-Turvy", "9017C754"),
    StickerData("Paratroopa", "Super Paper Mario", "9017C756"),
    StickerData("Miniature Dachshund", "Nintendogs", "9017C758"),
    StickerData("Kirby", "Kirby Air Ride", "9017C75A"),
    StickerData("Hawke", "Advance Wars: DS", "9017C75C"),
    StickerData("Jeff", "EarthBound", "9017C75E"),
    StickerData("Wolf", "Star Fox Command", "9017C760"),
    StickerData("Female Pianta", "Super Mario Sunshine", "9017C762"),
    StickerData("Tom Nook", "Animal Crossing: WW", "9017C764"),
    StickerData("Jessica", "Trace Memory", "9017C766"),
    StickerData("Ooccoo", "Zelda: Twilight Princess", "9017C768"),
    StickerData("Roy", "Fire Emblem: The Binding Blade", "9017C76A"),
    StickerData("Eirika", "Fire Emblem: The Sacred Stones", "9017C76C"),
    StickerData("Darknut", "Zelda: Wind Waker", "9017C76E"),
    StickerData("Blue Virus", "Nintendo Puzzle Collection", "9017C770"),
    StickerData("Moltres", "Pokémon series", "9017C772"),
    StickerData("Water Fairy Elias", "Nintendo Puzzle Collection", "9017C774"),
    StickerData("Bellossom", "Pokémon series", "9017C776"),
    StickerData("Squeaker", "Kirby: Squeak Squad", "9017C778"),
    StickerData("Karate Kong", "DK Jungle Beat", "9017C77A"),
    StickerData("Zinger", "DK: King of Swing", "9017C77C"),
    StickerData("Count Bleck", "Super Paper Mario", "9017C77E"),
    StickerData("Link", "Zelda: Link to the Past", "9017C780"),
    StickerData("Onion", "Pikmin 2", "9017C782"),
    StickerData("Brier", "Yoshi Touch & Go", "9017C784"),
    StickerData("Treasure Chest", "Kirby: Squeak Squad", "9017C786"),
    StickerData("The President", "Pikmin 2", "9017C788"),
    StickerData("Gardevoir", "Pokémon series", "9017C78A"),
    StickerData("Midna", "Zelda: Twilight Princess", "9017C78C"),
    StickerData("Maxim Tomato", "Kirby: Squeak Squad", "9017C78E"),
    StickerData("Samurai Goroh", "F-Zero X", "9017C790"),
    StickerData("Peach & Daisy", "Mario Party 7", "9017C792"),
    StickerData("1-Up Mushroom", "New SMB", "9017C794"),
    StickerData("Meryl Silverburgh", "MGS: The Twin Snakes", "9017C796"),
    StickerData("Boomerang", "Zelda: Wind Waker", "9017C798"),
    StickerData("Wario & Bike", "WarioWare: MMG", "9017C79A"),
    StickerData("Metal Gear RAY", "MGS2: Sons of Liberty", "9017C79C"),
    StickerData("Tortimer", "Animal Crossing: WW", "9017C79E"),
    StickerData("Falco", "Star Fox: Assault", "9017C7A0"),
    StickerData("Eight Yoshis", "SMA 3: Yoshi's Island", "9017C7A2"),
    StickerData("Ashley", "WarioWare: Touched!", "9017C7A4"),
    StickerData("Falco", "Star Fox Command", "9017C7A6"),
    StickerData("Deke", "Fire Emblem: The Binding Blade", "9017C7A8"),
    StickerData("Krystal", "Star Fox Adventures", "9017C7AA"),
    StickerData("White Cat", "F-Zero GX", "9017C7AC"),
    StickerData("Black Shadow", "F-Zero GX", "9017C7AE"),
    StickerData("Munchlax", "Pokémon series", "9017C7B0"),
    StickerData("Red Pikmin", "Pikmin", "9017C7B2"),
    StickerData("Olimar's Daughter", "Pikmin 2", "9017C7B4"),
    StickerData("Blue Pellet", "Pikmin 2", "9017C7B6"),
    StickerData("Wario World Symbol", "Wario World", "9017C7B8"),
    StickerData("Raiden", "MGS2: Sons of Liberty", "9017C7BA"),
    StickerData("Lion", "Game & Watch", "9017C7BC"),
    StickerData("Robot & Blocks", "Stack-Up", "9017C7BE"),
    StickerData("Ashnard", "Fire Emblem: Path of Radiance", "9017C7C0"),
    StickerData("Capt. Falcon", "F-Zero", "9017C7C2"),
    StickerData("Tippi", "Super Paper Mario", "9017C7C4"),
    StickerData("Samurai Goroh", "F-Zero", "9017C7C6"),
    StickerData("Sothe", "Fire Emblem: Radiant Dawn", "9017C7C8"),
    StickerData("Cornimer", "Animal Crossing: WW", "9017C7CA"),
    StickerData("Classic Sonic", "Sonic The Hedgehog JP Ver.", "9017C7CC"),
    StickerData("Wave the Swallow", "Sonic Riders", "9017C7CE"),
    StickerData("Emerl", "Sonic Battle", "9017C7D0"),
    StickerData("Jigglypuff", "Pokémon series", "9017C7D2"),
    StickerData("Sheik", "Zelda: Ocarina of Time", "9017C7D4"),
    StickerData("Green Rupee", "Zelda: Twilight Princess", "9017C7D6"),
    StickerData("Gulliver", "Animal Crossing: WW", "9017C7D8"),
    StickerData("Wolfen", "Star Fox: Assault", "9017C7DA"),
    StickerData("Waluigi", "Super Mario Strikers", "9017C7DC"),
    StickerData("Peach", "Mario Strikers Charged", "9017C7DE"),
    StickerData("Tikal", "Sonic Adventure Director's Cut", "9017C7E0"),
    StickerData("Rayquaza", "Pokémon series", "9017C7E2"),
    StickerData("Olimar & Louie's Ship", "Pikmin 2", "9017C7E4"),
    StickerData("Petey Piranha", "Mario Golf: TT", "9017C7E6"),
    StickerData("Space Pirate", "Super Metroid", "9017C7E8"),
    StickerData("Flag Man", "Game & Watch", "9017C7EA"),
    StickerData("Super Sonic", "Sonic The Hedgehog 2", "9017C7EC"),
    StickerData("Silver the Hedgehog", "Sonic The Hedgehog", "9017C7EE"),
    StickerData("Master", "Trade & Battle: Card Hero", "9017C7F0"),
    StickerData("Big Boss", "MGS: The Twin Snakes", "9017C7F2"),
    StickerData("Chaos", "Sonic Adventure Director's Cut", "9017C7F4"),
    StickerData("Federation Trooper", "Metroid Prime 2 Echoes", "9017C7F6"),
    StickerData("Running Chibi-Robo", "Chibi-Robo", "9017C7F8"),
    StickerData("Boo", "Mario Tennis", "9017C7FA"),
    StickerData("Ryuta Ippongi", "Ouendan 2", "9017C7FC"),
    StickerData("Phyllis", "Animal Crossing: WW", "9017C7FE"),
    StickerData("Liquid Snake", "MGS: The Twin Snakes", "9017C800"),
    StickerData("Goron", "Zelda: Ocarina of Time", "9017C802"),
    StickerData("Pauline & Donkey Kong", "Donkey Kong", "9017C804"),
    StickerData("Manky Kong", "Donkey Kong Country", "9017C806"),
    StickerData("Waddle Dee Ball", "Kirby Canvas Curse", "9017C808"),
    StickerData("Tiny Kong", "DK64", "9017C80A"),
    StickerData("Mario", "Mario Kart DS", "9017C80C"),
    StickerData("Medli", "Zelda: Wind Waker", "9017C80E"),
    StickerData("Octorok", "Zelda: Ocarina of Time", "9017C810"),
    StickerData("Turbo Birdo", "Mario Kart: DD!!", "9017C812"),
    StickerData("Zant", "Zelda: Twilight Princess", "9017C814"),
    StickerData("Wolf", "Excite Truck", "9017C816"),
    StickerData("Chonmagyo", "Densetsu no Stafy 2", "9017C818"),
    StickerData("Morph Ball", "Metroid Pinball", "9017C81A"),
    StickerData("Stork", "Yoshi's Island DS", "9017C81C"),
    StickerData("Yoshi's Egg", "Yoshi Touch & Go", "9017C81E"),
    StickerData("Koopa", "Super Mario Strikers", "9017C820"),
    StickerData("Bronto Burt", "Kirby 64", "9017C822"),
    StickerData("Car Yoshi", "Yoshi's Island", "9017C824"),
    StickerData("Fox", "Star Fox Adventures", "9017C826"),
    StickerData("Yoshi", "Yoshi Touch & Go", "9017C828"),
    StickerData("Dash", "Star Fox Command", "9017C82A"),
    StickerData("Katrina", "Animal Crossing: WW", "9017C82C"),
    StickerData("Boney", "Mother 3", "9017C82E"),
    StickerData("Salsa", "Mother 3", "9017C830"),
    StickerData("Lloyd", "Mother", "9017C832"),
    StickerData("Kyle Hyde", "Hotel Dusk: Room 215", "9017C834"),
    StickerData("Misstar", "Mario Party 5", "9017C836"),
    StickerData("Rusl", "Zelda: Twilight Princess", "9017C838"),
    StickerData("Electrode", "Pokémon series", "9017C83A"),
    StickerData("Gunship", "Metroid Prime 2 Echoes", "9017C83C"),
    StickerData("Fierce Deity Link", "Zelda: MM", "9017C83E"),
    StickerData("Moblin", "Zelda: Wind Waker", "9017C840"),
    StickerData("Guy", "Fire Emblem", "9017C842"),
    StickerData("Hero's Bow", "Zelda: Twilight Princess", "9017C844"),
    StickerData("Ana", "WarioWare: Touched!", "9017C846"),
    StickerData("Luigi", "Super Paper Mario", "9017C848"),
    StickerData("Capsule", "Nintendo Puzzle Collection", "9017C84A"),
    StickerData("Saharah", "Animal Crossing: WW", "9017C84C"),
    StickerData("Prince Peasley", "Mario & Luigi: SS", "9017C84E"),
    StickerData("Mega Rush Badge", "Paper Mario: TTYD", "9017C850"),
    StickerData("Postman", "Zelda: Majora's Mask", "9017C852"),
    StickerData("Sylux", "Metroid Prime Hunters", "9017C854"),
    StickerData("Young Zelda", "Zelda: Minish Cap", "9017C856"),
    StickerData("Perara", "Kirby: Squeak Squad", "9017C858"),
    StickerData("Rutoga", "Fire Emblem: The Binding Blade", "9017C85A"),
    StickerData("Akuma", "Sennen Kazoku", "9017C85C"),
    StickerData("Muskular", "Mario Party 5", "9017C85E"),
    StickerData("Hayato Saionji", "Ouendan 2", "9017C860"),
    StickerData("Shadow Mario", "Super Mario Sunshine", "9017C862"),
    StickerData("Twila", "Mario Party 6", "9017C864"),
    StickerData("Putty", "Magical Starsign", "9017C866"),
    StickerData("Dr. Shrunk", "Animal Crossing: WW", "9017C868"),
    StickerData("Donkey Kong", "DK Jungle Beat", "9017C86A"),
    StickerData("Judge", "Game & Watch", "9017C86C"),
    StickerData("Pascal", "Animal Crossing: WW", "9017C86E"),
    StickerData("Dice Block", "Mario Party 8", "9017C870"),
    StickerData("Diddy Kong", "Mario Hoops 3-on-3", "9017C872"),
    StickerData("Arwing", "Star Fox 64", "9017C874"),
    StickerData("Duster", "Mother 3", "9017C876"),
    StickerData("Helibokaan", "Kururin Squash!", "9017C878"),
    StickerData("Gravity Suit Samus", "Metroid: Zero Mission", "9017C87A"),
    StickerData("Hookshot", "Zelda: Ocarina of Time", "9017C87C"),
    StickerData("Ezlo", "Zelda: Minish Cap", "9017C87E"),
    StickerData("Tap-Tap", "Yoshi Touch & Go", "9017C880"),
    StickerData("Snifit", "Mario Party 3", "9017C882"),
    StickerData("Devil Car", "Mother", "9017C884"),
    StickerData("Paula", "EarthBound", "9017C886"),
    StickerData("Pigmask", "Mother 3", "9017C888"),
    StickerData("Wario", "WarioWare: Smooth Moves", "9017C88A"),
    StickerData("Krystal", "Star Fox Command", "9017C88C"),
    StickerData("Tameo", "Trade & Battle: Card Hero", "9017C88E"),
    StickerData("Ephraim", "Fire Emblem: The Sacred Stones", "9017C890"),
    StickerData("Rover", "Animal Crossing: WW", "9017C892"),
    StickerData("Peach", "Mario Superstar Baseball", "9017C894"),
    StickerData("Volvoice", "Electroplankton", "9017C896"),
    StickerData("Torchic", "Pokémon series", "9017C898"),
    StickerData("Snowman", "1080° Avalanche", "9017C89A"),
    StickerData("Akari Hayami", "Wave Race BS", "9017C89C"),
    StickerData("Ivysaur", "Pokémon series", "9017C89E"),
    StickerData("King Dedede & Kirby", "Kirby 64", "9017C8A0"),
    StickerData("Blargg", "Yoshi's Story", "9017C8A2"),
    StickerData("Mona & Moped", "WarioWare: MMG", "9017C8A4"),
    StickerData("Tamagon", "Devil World", "9017C8A6"),
    StickerData("Sparrow", "Magical Starsign", "9017C8A8"),
    StickerData("Diddy Kong", "DK64", "9017C8AA"),
    StickerData("Triple Red Shells", "Mario Kart: DD!!", "9017C8AC"),
    StickerData("Raccoon Mario", "Super Mario Bros. 3", "9017C8AE"),
    StickerData("Gray Fox", "MGS: The Twin Snakes", "9017C8B0"),
    StickerData("Hiroshi", "Trade & Battle: Card Hero", "9017C8B2"),
    StickerData("Rotohex", "Digiluxe", "9017C8B4"),
    StickerData("Ridley", "Metroid: Zero Mission", "9017C8B6"),
    StickerData("Skulltula", "Zelda: Ocarina of Time", "9017C8B8"),
    StickerData("Naomi Hunter", "MGS: The Twin Snakes", "9017C8BA"),
    StickerData("Waddle Dee", "Kirby 64", "9017C8BC"),
    StickerData("Blood Falcon", "F-Zero GX", "9017C8BE"),
    StickerData("Mr. Resetti", "Animal Crossing: WW", "9017C8C0"),
    StickerData("Millennium Star", "Mario Party 3", "9017C8C2"),
    StickerData("Horse Call", "Zelda: Twilight Princess", "9017C8C4"),
    StickerData("Colonel", "MGS2: Sons of Liberty", "9017C8C6"),
    StickerData("Don Bongo", "Yoshi's Story", "9017C8C8"),
    StickerData("Samus", "Metroid Prime 2 Echoes", "9017C8CA"),
    StickerData("Meta Knight", "Kirby: Squeak Squad", "9017C8CC"),
    StickerData("Revolver Ocelot", "MGS2: Sons of Liberty", "9017C8CE"),
    StickerData("Skull Kid", "Zelda: Ocarina of Time", "9017C8D0"),
    StickerData("Candy", "Kirby: Squeak Squad", "9017C8D2"),
    StickerData("Falco", "Star Fox Adventures", "9017C8D4"),
    StickerData("Donkey Kong", "Mario Kart DS", "9017C8D6"),
    StickerData("DK Barrel", "Donkey Kong Country", "9017C8D8"),
    StickerData("Luigi", "Luigi's Mansion", "9017C8DA"),
    StickerData("Raphael the Raven", "Yoshi's Island", "9017C8DC"),
    StickerData("Nabaaru", "Fire Emblem: Monsho no Nazo", "9017C8DE"),
    StickerData("Mario", "Mario Superstar Baseball", "9017C8E0"),
    StickerData("Wario", "Super Mario Strikers", "9017C8E2"),
    StickerData("Legend of Outset", "Zelda: Wind Waker", "9017C8E4"),
    StickerData("Excitebike", "Excitebike", "9017C8E6"),
    StickerData("Mace Guy", "Yoshi Topsy-Turvy", "9017C8E8"),
    StickerData("Hammer Bro", "New Super Mario Bros.", "9017C8EA"),
    StickerData("Kraid", "Metroid: Zero Mission", "9017C8EC"),
    StickerData("Goonie", "Yoshi's Island DS", "9017C8EE"),
    StickerData("Classic Sonic", "Sonic The Hedgehog US Ver.", "9017C8F0"),
    StickerData("Yoshi", "Paper Mario: TTYD", "9017C8F2"),
    StickerData("Barkle", "Tingle's Rupeeland", "9017C8F4"),
    StickerData("Acro", "Kirby 64", "9017C8F6"),
    StickerData("Vivian", "Paper Mario: TTYD", "9017C8F8"),
    StickerData("Hector", "Fire Emblem", "9017C8FA"),
    StickerData("Pikachu", "Pokémon series", "9017C8FC"),
    StickerData("Lucario", "Pokémon series", "9017C8FE"),
    StickerData("Squirtle", "Pokémon series", "9017C900"),
    StickerData("Bulborb", "Pikmin 2", "9017C902"),
    StickerData("Crimson Candypop Bud", "Pikmin 2", "9017C904"),
    StickerData("Kritter", "Mario Strikers Charged", "9017C906"),
    StickerData("Naked Snake", "MGS3: Snake Eater", "9017C908"),
    StickerData("Wave Race Blue Storm", "Wave Race: Blue Storm", "9017C90A"),
    StickerData("Piece of Heart", "Zelda: Twilight Princess", "9017C90C"),
    StickerData("Metal Gear REX", "MGS: The Twin Snakes", "9017C90E"),
]
